In [11]:
def fibonacci_recursive(n: int) -> int:
    """
    n번째 피보나치 수를 재귀적으로 계산하여 반환합니다.
    (F(0)=0, F(1)=1 기준)

    주의: 이 순수 재귀 방식은 n이 커질수록 동일한 계산을 반복하여
          매우 비효율적입니다 (시간 복잡도 O(2^n)).
          실제 사용 시에는 메모이제이션(동적 프로그래밍)을 사용한 최적화가 필요합니다.

    재귀함수는 기본적으로 스택 구조처럼 이동.
    """
    if not isinstance(n, int) or n < 0: # n이 인트인가? isinstance(n,int)
        raise ValueError("입력값은 0 이상의 정수여야 합니다.") # 에러가 보이도록 만들기
    if n <= 1:  # 기본 조건: F(0) = 0, F(1) = 1
        return n
    else:
        # F(n) = F(n-1) + F(n-2)
        return fibonacci_recursive(n - 1) + fibonacci_recursive(n - 2)
    
fibonacci_recursive(3)

help(fibonacci_recursive)

Help on function fibonacci_recursive in module __main__:

fibonacci_recursive(n: int) -> int
    n번째 피보나치 수를 재귀적으로 계산하여 반환합니다.
    (F(0)=0, F(1)=1 기준)
    
    주의: 이 순수 재귀 방식은 n이 커질수록 동일한 계산을 반복하여
          매우 비효율적입니다 (시간 복잡도 O(2^n)).
          실제 사용 시에는 메모이제이션(동적 프로그래밍)을 사용한 최적화가 필요합니다.
    
    재귀함수는 기본적으로 스택 구조처럼 이동.



In [12]:
# 재귀 버전 테스트
if __name__ == "__main__":
    print("재귀 버전 피보나치 수열 (n번째 수):")
    for i in range(10): # 0부터 9번째 피보나치 수까지 출력
        # n이 커지면 매우 느려지므로 작은 범위에서 테스트
        if i < 20: # 실제로는 15-20만 넘어가도 눈에 띄게 느려짐
             print(f"F({i}) = {fibonacci_recursive(i)}")
        else:
            print(f"F({i}) 계산은 재귀 방식으로는 매우 오래 걸릴 수 있습니다.")
            break
    
    # 예: F(10) 계산
    # print(f"\nF(10) = {fibonacci_recursive(10)}") # 55
    # print(f"F(30) = {fibonacci_recursive(30)}") # 이 계산은 상당히 오래 걸립니다!

재귀 버전 피보나치 수열 (n번째 수):
F(0) = 0
F(1) = 1
F(2) = 1
F(3) = 2
F(4) = 3
F(5) = 5
F(6) = 8
F(7) = 13
F(8) = 21
F(9) = 34


# 시간복잡도


In [13]:
import numpy as np

np.array([1,2,3,4,5]) * 2

array([ 2,  4,  6,  8, 10])

In [14]:
np.arange(20).reshape(4,5) # ndim 차원을 이야기함, shape -> 형태 arange(n) -> 갯수만큼 만들기 
np.arange(20).reshape(-1,5) # -1하면 알아서 채워줌.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
np.arange(20).reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [16]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
a = np.arange(20,80,10)
b = sum(a)/len(a)
[x- 45.0 for x in a]

np.mean(a) # 평균
np.var(a) # 분산 : 각각의 값에서 평균 / 편차의 합은 항상 0 
np.std(a) # 표준편차 : 편차의 제곱의 평균

np.float64(17.07825127659933)

In [18]:
# import zipfile
# import os, shutil, pathlib

# pathlib.Path("./cusomter/male").mkdir(parents =True, exist_ok=True)
# pathlib.Path("./cusomter/male").mkdir(parents =True, exist_ok=True)
# name = os.listdir("./data/이름_생년_성별_10000")

# for file in name :
#     if file.split("_")[-1][0] in ['1','3']:
#         with open(f"./name/{file}","r") as f:
#             print(int(f.read().reaplec(",","")))


In [19]:
with open("./myfilelsit.txt", 'w', encoding='utf-8') as f :
    for roots, dirs, files in os.walk("c:/windows/"):
        for file in files:
            f.write(f"{roots}{file}\n")
    f.close()


In [20]:
import zipfile
with zipfile.ZipFile("./이름_생년_성별_10000.zip") as f:
    f.extractall("./name")

pathlib.Path("./cusomter/male").mkdir(parents=True, exist_ok=True)
pathlib.Path("./cusomter/female").mkdir(parents=True, exist_ok=True)
male = []
female = []
for file in os.listdir("./name"):
    # 남성
    if file.split("_")[-1][0] in ['1', '3']:
        with open(f"./name/{file}", "r") as f:
            male.append(int(f.read().replace(",", "")))
        shutil.move(f"./name/{file}", f"./cusomter/male/{file}" )
    elif file.split("_")[-1][0] in ['2', '4']:
        with open(f"./name/{file}", "r") as f:
            female.append(int(f.read().replace(",", "")))
        shutil.move(f"./name/{file}", f"./cusomter/female/{file}" )
    else:
        print("잘못된 파일입니다. ")


In [22]:
a=np.mean(female)
b=np.mean(male)

print(a,b)

12802368.483323347 11900177.712397356


# 리눅스 사용법
설치 wsl -install Ubuntu-버전

wget 설치하려는 다운로드 주소 -> 설치
cli 환경에서 써봤나요? -> 리눅스써본적 있나여

ping 8.8.8.8 (구글 서버)

source ~/.bashrc -> 베이스 환경 만들기

"r" 읽기 "w" 쓰기 "x"는 실행 권한 

파일 앞에 . -> 숨겨진 파일

3개 단위로 끊어서 읽기.